from random import choice
from preambles import preambles
from maleGenitals import maleGenitals

doThingsToHisGenitals = [
  preambles,
  " ",
  [
    "Punch",
    "Bite",
    "Kick",
    "Poke",
    "Belittle",
    "Humiliate",
    "Spit on",
    "Lick",
    "Have contempt for",
    "Suck",
    "Massage",
    "Hypnotize",
    "Livestream",
    "Skin",
    "Paint",
    "Toast",
    "Roll",
    "Blend",
    "Imagine",
    "Critique",
    "Corkscrew",
    "Experiment with",
    "Mock",
    "Shape",
    "Spin",
    "Tickle",
    "Bounce",
    "Wiggle",
    "Review"
  ],
  " his ",
  maleGenitals,
  " until he ",
  [
    "asks you to stop.",
    "begs you to stop.",
    "wishes you would stop.",
    "summons a genie to get you to stop.",
    "gets bored of it.",
    "calls Amnesty International.",
    "cries.",
    "regrets meeting you.",
    "gets creeped out.",
    "accepts you as his new God.",
    "notices.",
    "wakes up.",
    "finally enjoys it.",
    "bursts into song",
    "calls you Mother.",
    "folds into singularity.",
    "returns to dust.",
    "runs out of quarters.",
    "remembers you exist.",
    "trancends to a new plane.",
    "runs out of the house screaming.",
    "reconsiders a kind and loving god.",
    "has to go on set.",
    "detaches his penis and escapes.",
    "his penis falls off and sprouts two heads in its place.",
    "loans you his Playstation.",
    "admits pineapple is an acceptable pizza topping.",
    "unplugs you from the wall.",
    "sings the entirety of \"I Am the Very Model of a Modern Major General\".",
    "buys that mixer you've been asking for.",
    "hands over the microfiche.",
    "remembers your anniversary.",
    "finally reveals the secret Coke recipe.",
    "admits that he faked his Xbox gamer score.",
    "scratches your nipples like a DJ turntable.",
    "starts fingering a jar of silly putty.",
    "gives you the pizza for free.",
    "curls up into a defensive position.",
    "is found Not Guilty by a jury of his peers.",
    "penis ejects a tiny red BANG flag.",
    "quits having sex with his girlfiend.",
    "hears a fanfare play in the background.",
    "gets fed up and does it himself.",
    "ski-bi dibby dib yo da dub dubs into orgasm.",
    "lets you leave the bunker.",
    "accepts \"zanxorb\". Double letter score on Z, triple word score, that's 105 points!",
    "passes out.",
    "agrees that Tonya Harding is the better skater.",
    "sobs quietly in the corner.",
    "writes in to Penthouse Forum.",
    "puts down the Hatsune Miku figurine.",
    "considers celibacy.",
    "the seven dwarves return from their labors in the mine.",
    "he summons a horde of zombies to pull you both into hell.",
    "he cuts off your head and absorbs your essence.",
    "retweets your joke."
  ]
]

dothingtohisgenitals = choice(doThingsToHisGenitals[0]) + doThingsToHisGenitals[1] + choice(doThingsToHisGenitals[2]) + doThingsToHisGenitals[3] + choice(doThingsToHisGenitals[4]) + doThingsToHisGenitals[5] + choice(doThingsToHisGenitals[6])

