from random import choice
fakeNames = {
  'first': {
    'men': [
      "Clifton",
      "Alistair",
      "Crunk",
      "Dag",
      "Brock",
      "Slug",
      "Dick",
      "P.J.",
      "Tungsten",
      "F. Murray",
      "Grund",
      "Thurston",
      "Crud",
      "Sandford",
      "Peter B",
      "Satch",
      "Philbert"
    ],
    'women': [
      "Whinnie",
      "Siri",
      "Bimbi",
      "Tawnee",
      "Kaytee",
      "Stacie",
      "Katrina",
      "Gwenevere",
      "Annie",
      "Phoebe",
      "Femke",
      "Flavia",
      "Nestea",
      "Fanta",
      "Sandy",
      "Sammi",
      "Pansy",
      "Brindle",
      "Swank"
    ]
  },
  'last': [
    "Nutskin",
    "Slapandtickle",
    "Dickwhistle",
    "Realperson",
    "Shrunkendink",
    "Fluffermore",
    "Gutbucket",
    "Turnblatt",
    "Dingle-Schmidt",
    "Thistlewick",
    "Bundlebottom",
    "Troublelump",
    "Ornithopter",
    "Innercheese",
    "Winnerlose",
    "Tremblecleft",
    "Cliff-Note",
    "Strunkenwhite",
    "Arr",
    "Genuine",
    "Blank-Schotte",
    "Christchurch",
    "Odor",
    "Actual",
    "Peelinete",
    "Pfistre",
    "Scuntpunsch"
  ]
}
#print choice(fakeNames['last'])
#print choice(fakeNames['first']['men'])
