from random import choice

newSexPositions = [
  [
    "Try out a new position:",
    "Have sex in a new position:",
    "Ditch the missionary!",
    "Forget the kama sutra, try this one:",
    "If you\'re daring:",
    "If you\'re up for a challenge:",
    "Get yourself into one of these hardcore positions:",
    "Make your next romp one to remember:",
    "Take your sex from bleh to BAM:",
    "Dr. Honeypot recommends:"
  ],
  " Put your legs ",
  [
    "over his head",
    "around his butt",
    "on top of his legs",
    "on his knees",
    "over his gun rack",
    "all around his body",
    "aside",
    "out the window",
    "around your neck",
    "on the jungle gym",
    "on the pillow",
    "in the CAT position",
    "on the kitchen table",
    "on the coffee table",
    "on the repilca Great Pyramid of Giza",
    "on the door jamb",
    "on his Dragonlance collection",
    "through the steering wheel",
    "in the stirrups",
    "in the crane position",
    "in the lotus position",
    "in a frenzy",
    "over his shoulders",
    "on the fishtank",
    "on the radiator",
    "on his essential oils collection"
  ],
  " and your hands ",
  [
    "on his head",
    "gripping his butt cheeks",
    "grabbing his legs",
    "squeezing his knees",
    "resting on his balls",
    "around his aura",
    "on his hip",
    "over his eyes",
    "in his chest cavity",
    "in his mouth",
    "on your phone",
    "in a box of Cheez-Its",
    "on the Bible",
    "against his pubic bone",
    "in a pair of wool mittens",
    "in his buttcrack",
    "around his tulpa",
    "around your breasts",
    "on your trusty six shooter",
    "anywhere warm",
    "on his temples",
    "on his testicles",
    "on his pecs",
    "around his throat",
    "on your foam cowboy hat",
    "on a stopwatch",
    "on your cheeks in a Home Alone expression"
  ],
  ". ",
  [
    "Now thrust back against him as hard as you can.",
    "Now lay perfectly still until he forgets you\'re in the room.",
    "Now stare him right in the eyes and dare him to make love to you like that.",
    "Now tell him to orgasm on the count of three.",
    "Now begin a high pitched shriek daring him to knock you unconscious.",
    "Now fire a starter pistol.",
    "Now grind your clitoris into a fine paste.",
    "Now make a bridge with your genitals.",
    "Now don\'t forget the asshole!",
    "Now neglect to mention your affair.",
    "Now embrace the ~~**~~uNiCoRn oRgAsM~~**~~ within.",
    "Now prepare a fine meal for our guest judges using the mystery ingredient Hot Cheetos.",
    "Now lay back and think of England",
    "Now ask your partner for a spot.",
    "Now execute the legendary quadruple salchow onto the bed.",
    "Now search for that ring you lost inside him but haven\'t brought up the courage to say.",
    "Now engulf the both of you in a silk cocoon to complete the metamorphasis.",
    "Now compete in the 17th Annual Company Sack Race.",
    "Now wake up from your nightmare, having remembered nothing but sadness.",
    "Now reconsider all of the life choices you\'ve made up \'til now.",
    "Now fight to the death for the claim to the throne.",
    "Now long for the sweet release of death.",
    "Now get jumpin and bumpin and pumpin and moving all around.",
    "Now ram your genitals together like a game of Hungry Hungry Hippos.",
    "Now lick anything you can reach.",
    "Now realize that you will never be as funny as Lasagna Cat.",
    "Now slam a beer and crush the can on his head.",
    "Now give him the ol\' razzle dazzle!",
    "Now create shadow puppets with your genitals.",
    "Now you know your hips don\'t lie and you\'re starting to feel it\'s right.",
    "Now get low. Get low. Get low. Get low.",
    "Now declare yourself the conqueror of Fuck Mountain.",
    "Now perform a courtesy pee.",
    "Now you\'re ready to use the ouija board.",
    "Now put a fig leaf on your genitals and reenact the fall of man.",
    "Now balance on a Pogo Ball and still manage to orgasm.",
    "Now consult your horoscope for the appropriate amount of touching.",
    "Now throw glitter over everything, turning your session into a disco fuck festival.",
    "Now braid your hair into a set of reigns and Hi Ho Silver, Fuck Away!",
    "Now twirl, damn it twirl! If you stop twirling he won\'t love you anymore.",
    "Now complain that it\'s too cold in the room, but don\'t do anything to change it.",
    "Now stop what you\'re doing entirely and move the lamps, the Feng Shui is ALL WRONG.",
    "Now consult your Sex Coach via Skype for some hot tips.",
    "Now control your own erotic destiny and masturbate to orgasm before he can finish.",
    "Now put your right butt cheek on red, left labia on yellow.",
    "Now accidentally catch on fire from the hundreds of candles you have around the bedroom.",
    "Now present your perfectly formatted MLA bibliography for tonight\'s sex positions."
  ],
  " ",
  [
    "What a workout!",
    "How transcendental!",
    "Soon you\'ll be another story in Hustler!",
    "Your yoga class will be impressed!",
    "Hotter than hot!!",
    "This makes for an explosive orgasm!",
    "Like a science experiment!",
    "You never knew your body could bend that way!",
    "Sensational sensations!",
    "He\'ll thank you later!",
    "Just like a porn star!"
  ]
]

newsexposition = choice(newSexPositions[0]) + newSexPositions[1] + choice(newSexPositions[2]) + newSexPositions[3] + choice(newSexPositions[4]) + newSexPositions[5] + choice(newSexPositions[6]) + newSexPositions[7] + choice(newSexPositions[8]) 

print newsexposition

