var blowjobs = [
  [
    "And now, the perfect blowjob:",
    "Mind blowing oral for him:",
    "The Perfect Blowjob:",
    "Give him a blowjob to remember:",
    "The Best Blowjob He's Ever Had:",
    "A super-secret oral tip from us:",
    "This blowjob is 💯:"
  ],
  " ",
  [
    "While his penis is in your mouth",
    "With his penis in your mouth",
    "As you suck on his penis",
    "With the head of his penis in your mouth"
  ],
  ", ",
  [
    "snap your fingers at him like you were Calista Gingrich summoning a waiter",
    "slap him once on each side of his face",
    "look directly into one of his eyes (your choice)",
    "wink seductively at him",
    "twist his scrotum around a chopstick or paintbrush",
    "gag just a little bit",
    "apologize for what you're about to do",
    "hum the chorus to the Hanson song Mmm-Bop",
    "load your mouth up with caltrops",
    "fill your mouth with crushed pineapple",
    "tickle his nipple",
    "start chewing some gum",
    "activate your camouflage",
    "mush his balls into a single undiscernable shape",
    "examine his belly button with a magnifying glass",
    "dump soap on his dick because he's a dirty boy",
    "shave his pubes",
    "toot the <i>Robin Hood</i> Oo De Lally song on his penis",
    "tap S.O.S. with your tongue",
    "make Pac-Man WAKA WAKA noises as you move down the shaft",
    "lie profusely about the size and smell",
    "do the chicken dance with your arms",
    "tie your hair tightly around his scrotum",
    "stick your finger in his navel",
    "squish his flab to make a frowny face in the love handles",
    "give him a play-by-play of the blowjob John Madden-style",
    "stand up because it's more ergonomic",
    "practice your tuvan throat singing",
    "play with his testicles like a Newton's cradle",
    "crush Kinder eggs with your hands in full view",
    "flap your hands on his hips and make elephant noises",
    "pierce his frenulum"
  ],
  " and ",
  [
    "knock the tip of his penis against your uvula as though it was a prize fighter practicing on a speed bag.",
    "bite down.",
    "then spit his penis out of your mouth.",
    "then file for divorce.",
    "spin around his penis like you're in a dizzy bat race.",
    "dig your fingernails into his scrotum.",
    "cut off all your hair.",
    "then try to inflate his penis like a balloon.",
    "suck in on his urethra to remove his life essense.",
    "twiddle your fingers on the shaft like it was a flute.",
    "press it in a scrapbook to preserve the memories.",
    "press up, down, up, down, left, right, left, right, testicle, testicle, dick.",
    "hum “Taps” while slowly sliding off his penis onto the floor.",
    "mime revving a motor while you give his scrotum a raspberry.",
    "screech at his penis as if you're protecting your young.",
    "move side to side, blocking him from a layup.",
    "pantomime drowning.",
    "grow a pointy mustache and rub a melted clock on his balls. This is very meaningful.",
    "go back to browsing Reddit.",
    "refuse to take any part of him seriously.",
    "roll a D20 for pleasure.",
    "rifle through his wallet, grabbing any loose cash.",
    "pantomime choking to death, and then steal his computer when he leaves to call an ambulance.",
    "fake a seizure.",
    "try to recite The Declaration of Independence.",
    "grab the sides of his scrotum and play them like an accordion.",
    "drink bourbon from the bottle with a straw.",
    "ask why it's covered in blue body paint.",
    "<i>then</i> take off his underwear.",
    "deflate slightly under the pressure.",
    "then do another line of coke.",
    "finish knitting a pair of socks.",
    "FINISH HIM.",
    "regret it later.",
    "post about it on Instagram.",
    "make the Price is Right “sad trombone” noise."
  ]
];
