var bondageTips = [
  [
    "Introduce a little kink into your life!",
    "Time to get naughty!",
    "Be his daring darling!",
    "Experiment with bondage!",
    "Be his darling dominatrix!"
  ],
  " ",
  [
    "Handcuff",
    "Tie",
    "Lash",
    "Restrain",
    "Clamp",
    "Duct tape"
  ],
  " his ",
  [
    "hands",
    "wrists",
    "ankles",
    "head",
    "thighs",
    "arms"
  ],
  " to ",
  [
    "the bed",
    "the the headboard",
    "the radiator",
    "the front door",
    "a meathook",
    "jungle gym",
    "a Ghostbusters® Lego® playset",
    "a nailed together stack of Jenga bricks",
    "two draft horses",
    "your spare sarcophagus",
    "a torture rack",
    "an iron maiden",
    "your neighbor Brian",
    "a dogsled",
    "a trampoline",
    "the mast of the USS Constitution",
    "a treehouse",
    "the larch",
    "the door jamb",
    "a stake",
    "an inflatable castle",
    "the United Nations building",
    "a full keg of Hidden Valley Ranch",
    "a Himalayan salt lamp",
    "your collection of antique bowling balls",
    "your cousin's wedding cake",
    "an antique lamp",
    "a large tesla coil",
    "a clothes drying rack",
    "a rickety deer blind",
    "a subwoofer",
    "a power substation",
    "the rafters",
    "the sex swing",
    "a tire swing",
    "two furious raccoons",
    "the toilet tank"
  ],
  " and ",
  [
    "leave.",
    "discuss what you'd like to change about the kitchen backsplash.",
    "give him one hard punch right in the taint.",
    "then have sex with his dad.",
    "tell him how excited you are about watching him starve to death.",
    "surprise him with your brand new blood play fetish.",
    "show him all of the photos from your vacation to Utah.",
    "invite in the Jehovah's Witnesses and let him hear the good news!",
    "put a Jeff Dunham special on repeat.",
    "put My Little Pony tattoos all over his body.",
    "reenact the stations of the cross.",
    "browse Tindr for someone more interesting.",
    "brick him in with the cask of Amontillado.",
    "sing 99 bottles of beer on the wall, without informing him you have dyscalculia.",
    "play him all your favorite PewDiePie videos.",
    "draw a magic circle and summon Satan.",
    "throw his prized collection of Fleshlights into the garbage disposal.",
    "say “.elyts ni kcab emoc ot gniog si ekil uoy mug tahT”",
    "start a larp of FATAL.",
    "close your eyes. As you count backwards from ten, ready yourself for the feeling you get when your knife tears into the flesh of another.",
    "turn off the lights and play creepy children's songs for six hours.",
    "read Fallout:Equestria with different voices for every character.",
    "triple combo kick his dick.",
    "slowly lower him into a vat of angry crabs.",
    "painstakingly paint a fresco of dicks all over his body.",
    "prank call all of his old girlfriends while on speakerphone.",
    "find out how many bananas will fit in his asshole.",
    "bark like a walrus while goring him with your pencil tusks.",
    "create a cast of his genitalia and sell it to a Chinese dildo manufacturer.",
    "put a pair of glasses on his penis and have a tea party.",
    "show him how much you've improved at playing the kalimba.",
    "workshop some new Cards Against Humanity suggestions.",
    "invest in a time share.",
    "binge-watch Season 12 of Supernatural.",
    "then a skeleton pops out!",
    "spin around with multiple whips in your hands, screaming “WASH CYCLE!”",
    "try out your new electro-shock dildo.",
    "Google how to dominatrix.",
    "roll out your pin board filled with evidence of the Illuminati.",
    "feed him recipes from your grandmother's Weight Watchers recipe cards.",
    "invite a local jam band to play while you fuck.",
    "lose the only keys to the steel handcuffs.",
    "show him all of your pokemons.",
    "tickle him with a feather and find out he has a severe goose allergy.",
    "start a STOMP jam session using his flesh as an instrument.",
    "realize you have no sex toys and sheepishly end the session.",
    "show off what you learned in the porno <i>American Horror Story</i>.",
    "list all of his emotional problems on a scratchy chalkboard.",
    "try to plug your braid into his anus.",
    "realize nobody is having any fun.",
    "remind him of all the embarassing things he did as a teenager.",
    "put a crown on his head and delare him King Dipshit.",
    "practice your knife throwing routine.",
    "mix him a Manhattan but put it in a wine glass.",
    "never stop teasing his penis, until it decends into schoolyard bullying.",
    "tattoo his name on your left breast, but spell it wrong.",
    "strap his penis and testicles to an even smaller rack, using tiny whips on them.",
    "go back to reading <i>Fifty Shades of Grey</i>.",
    "show him all of the latest memes.",
    "tell him you've replaced all of the lube with Sriracha mayo and go to town.",
    "read his high school diary out loud.",
    "throw an octopus on the floor and see how it goes.",
    "burn a several bags of popcorn and lock him in the room with them.",
    "put on a looping playlist of anime girl hip hop covers.",
    "crumble stale cookies all over the bed while he watches.",
    "put on reruns of <i>Bridezillas</i>.",
    "pontificate on the use of whitespace in Wikipedia's site design.",
    "quiz him about typeface kerning.",
    "unsuccessfully sync your partner's IOT buttplug to your phone.",
    "scatter his prized baseball cards while playing a loop of cats vomiting.",
    "put on a puppet show of his past sexual failures.",
    "saunter up to him sexily and immediately trip in your 12 inch hooker heels.",
    "stab him in the pinneal gland and steal his precious juice to become young again.",
    "just fuck up all of his chakras with bad crystals and a bunch of magnets.",
    "practice your newly acquired accupuncture skills from ez-accupunktooronline.com",
    "export all of his EDM remixes at the lowest bitrate and delete the FLAC.",
    "take off all the stickers on his Snapback hats.",
    "use clothespins to clip your underwear to his flesh for a sexy combo of housework and pain play.",
    "just load his dick up with all the chip clips in the house.",
    "fill his chest with clothe band aids and rip them all off."
  ]
];
