var danceForHim = [
  [
    "Show him your sultry moves:",
    "Dance moves to make your man melt:",
    "Strut your sexy stuff:"
  ],
    " Play ",
  [
    "<i>The Breakfast Machine</i>",
    "Gregorian chant",
    "the screaming of the damned",
    "the Kol Nidre",
    "the <i>Popcorn</i> song",
    "a recording of your economics course lecture",
    "Leonard Cohen's <i>Hallelujah</i>",
    "Gary Jules' <i>Mad World</i>",
    "the emergency broadcast signal",
    "<i>Turkey in the Straw</i>",
    "the <i>Silent Hill</i> soundtrack",
    "dial-up modem connection sound",
    "<i>Faerie's Air and Death Waltz</i>",
    "<i>Gilligan's Island</i> theme song",
    "your avant-garde jazz playlist",
    "whale sounds album",
    "Kriss Kross' <i>Jump</i>",
    "<i>Flight of the Bumblebee</i> played by kazoos",
    "Amon Amarth",
    "a chorus of children singing <i>Mary, Mary, Quite Contrary</i>",
    "a Grateful Dead guitar solo",
    "the Five Finger Family song",
    "a bootleg copy of ",
    "the Jingle Cats album",
    "the <i>Symphonies for Dog Whistles</i> album"
  ],
  " ",
  [
    "while seductively stripping out of your <i>Home Depot</i> uniform",
    "and dance with a live hive of African wasps",
    "and strip out of your meat dress",
    "and shuffle slowly from side to side, muttering 'this too will end'",
    "and do the most sombre Charlston he's ever seen",
    "while lumbering like a zombie about the room",
    "while twirling Nicholas Cage-shaped pasties",
    "while spinning on the floor like Curly, whooping loudly.",
    "and dance around with fans made out of houseplant leaves",
    "while spinning a cane and straw hat",
    "and tango with a mannequin in lingerie",
    "and juggle seven fire sticks",
    "and skank wildly in the corner",
    "and mimic a inflatable waving tube man",
    "and do a keg stand",
    "and drop to the floor and do the worm",
    "and flap your breasts like they were flags",
    "and do the Dance of the Seven Veils with used handkerchiefs",
    "and mosh pit tackle him out of his chair",
    "while slowly eating your pizza roll dress",
    "while dancing around with your leftover bachelorette party penis paraphanalia",
    "while twerking in an oversized penguin costume",
    "and start unrolling your linen mummy wrappings",
    "and slowly squeegee off the hair removal cream from your body",
    "while using interperate dance to talk about your day",
    "while using your gut rolls to pantomime singing",
    "and call upon your high school techno goth dance skills",
    "and whip around a set of glowsticks on shoestrings",
    "while rolling around in a pool of overcooked spaghetti",
    "while catching up on your burpees",
    "and dead eye stare him in the face while river dancing",
    "and summon a cadre of cirque du soleil to flank you",
    "while jiggling all of your loose flesh",
    "while shooting the ceiling with your finger guns",
    "and sway your hips to displace the creamed corn",
    "and start dancing on a disconnected DDR mat"
  ],
  ". ",
    "Get intimate at the end by ",
  [
    "jiggling",
    "twerking",
    "teasing",
    "blowtorching",
    "shimmying",
    "waving",
    "licking",
    "painting red",
    "strumming",
    "puppeteering",
    "revealing",
    "spinning"
  ],
  " your ",
  ladyBodyParts,
  " and ",
  [
    "taking out a subprime mortgage.",
    "rubbing your butt in his face.",
    "climbing into his tshirt.",
    "slithering like a snake on the floor.",
    "weep endlessly.",
    "screech until every glass explodes.",
    "shove a pineapple up his anus.",
    "awkwardly shoving your breasts in his face.",
    "circling him while making quacking noises.",
    "putting more clothes on.",
    "trip and sprain your ankle.",
    "cartwheel into the full length mirror.",
    "finally remove your chastity belt.",
    "hand him your pink slip.",
    "slowly back out of the room.",
    "set off the pyrotechnics display.",
    "topple the domino mural of ancient Roman porn.",
    "turn off the secret webcam.",
    "launch yourself down the Slip n' Slide into his penis.",
    "wash off all of the blood.",
    "wait for the judges' score.",
    "awkwardly rush back to the music before another song starts.",
    "sidle over the bed, glancing over at him.",
    "realize you left the blinds open this whole time.",
    "shoot him with a tshirt cannon filled with condoms.",
    "shout “TAH DAAAAAAAH!”",
    "find out he left fifteen minutes ago.",
    "topple out of his lap trying to unhook from the chair.",
    "present him with an itemized bill.",
    "ask him if he'd like fries with that.",
    "play your buttcheeks like a set of bongos.",
    "turn on your flashing LED bodysuit.",
    "turn your neck 360 degrees and devour his soul.",
    "go to give him a hickie but pierce is cartoid artery.",
    "fall asleep due to the effort.",
    "collapse into sexy singularity.",
    "rip off your undewear to reveal a skin colored bodysuit.",
    "sit down in a chair and say it's his turn.",
    "bring out a banjo to really start this hootenanny.",
    "plead for Jabba the Hutt to release you.",
    "fling your bra in his face like a rubber band.",
    "triple flip onto his penis.",
    "pick up your tips from the edge of the stage."
  ]
];
