var danceForHim = [
  [
    "Show him your sultry moves:",
    "Dance moves to make your man melt:",
    "Strut your sexy stuff:",
    "Give him a private show: "
  ],
  " Play ",
  [
    "<i>The Breakfast Machine</i>",
    "Gregorian chant",
    "the screaming of the damned",
    "the Kol Nidre",
    "the <i>Popcorn</i> song",
    "a recording of your economics course lecture",
    "Leonard Cohen's <i>Hallelujah</i>",
    "Gary Jules' <i>Mad World</i>",
    "the emergency broadcast signal",
    "<i>Turkey in the Straw</i>",
    "the <i>Silent Hill</i> soundtrack",
    "dial-up modem connection sound",
    "<i>Faerie's Air and Death Waltz</i>",
    "<i>Gilligan's Island</i> theme song",
    "your avant-garde jazz playlist",
    "a whale sounds album",
    "Kriss Kross' <i>Jump</i>",
    "<i>Flight of the Bumblebee</i> played by kazoos",
    "Amon Amarth",
    "a chorus of children singing <i>Mary, Mary, Quite Contrary</i>",
    "a Grateful Dead guitar solo",
    "the Five Finger Family song",
    "the Jingle Cats album",
    "the <i>Symphonies for Dog Whistles</i> album",
    "a warped country-western vinyl you found a Goodwill",
    "a <i>Kidz Bop</i> cd",
    "the sound of a thousand screaming rats",
    "<i>Yakety Sax</i>",
    "Khachaturian's Sabre Dance",
    "that funky music white boy",
    "your fifth grade recorder concert VHS",
    "<i>Paralyzer</i> on a series of floppy drives",
    "your playlist of Geocities midi files",
    "your voicemail inbox on repeat",
    "the marimbas"
  ],
  " ",
  [
    "while seductively stripping out of your <i>Home Depot</i> uniform",
    "and dance with a live hive of African wasps",
    "and strip out of your meat dress",
    "and shuffle slowly from side to side, muttering 'this too will end'",
    "and do the most sombre Charlston he's ever seen",
    "while lumbering like a zombie about the room",
    "while twirling Nicholas Cage-shaped pasties",
    "while spinning on the floor like Curly, whooping loudly",
    "and dance around with fans made out of houseplant leaves",
    "while spinning a cane and straw hat",
    "and tango with a mannequin in lingerie",
    "and juggle seven fire sticks",
    "and skank wildly in the corner",
    "and mimic a inflatable waving tube man",
    "and do a keg stand",
    "and drop to the floor and do the worm",
    "and flap your breasts like they were flags",
    "and do the Dance of the Seven Veils with used handkerchiefs",
    "and mosh pit tackle him out of his chair",
    "while slowly eating your pizza roll dress",
    "while dancing around with your leftover bachelorette party penis paraphanalia",
    "while twerking in an oversized penguin costume",
    "and start unrolling your linen mummy wrappings",
    "and slowly squeegee off the hair removal cream from your body",
    "while using interperate dance to talk about your day",
    "while using your gut rolls to pantomime singing",
    "and call upon your high school techno goth dance skills",
    "and whip around a set of glowsticks on shoestrings",
    "while rolling around in a pool of overcooked spaghetti",
    "while catching up on your burpees",
    "and dead eye stare him in the face while river dancing",
    "and summon a cadre of cirque du soleil dancers to flank you",
    "while jiggling all of your loose flesh",
    "while shooting the ceiling with your finger guns",
    "and sway your hips to displace the creamed corn",
    "and start dancing on a disconnected DDR mat",
    "while running a rented jackhammer",
    "and reenact the entirety of <i>Bring It On</>",
    "while spraying whipped cream wildly in the air",
    "and bust out of the life-sized pinata of yourself",
    "while spinning live snakes like nunchucks",
    "while swinging from the fan like a naked orangutan"
  ],
  ". Get intimate at the end by ",
  [
    "jiggling",
    "twerking",
    "teasing",
    "blowtorching",
    "shimmying",
    "waving",
    "licking",
    "painting red",
    "strumming",
    "puppeteering",
    "revealing",
    "spinning",
    "caressing",
    "fondling",
    "squishing",
    "wiggling",
    "presenting"
  ],
  " your ",
  ladyBodyParts,
  " while ",
  [
    "taking out a subprime mortgage.",
    "rubbing your butt in his face.",
    "climbing into his tshirt.",
    "slithering on the floor like a snake.",
    "weeping endlessly.",
    "screeching until all of the glass explodes.",
    "shoving a pineapple up his anus.",
    "awkwardly shoving your breasts in his face.",
    "circling his chair, honking like a Canadian goose.",
    "putting on more clothes.",
    "tripping over discarded clothing, spraining your ankle.",
    "cartwheeling into the full length mirror.",
    "finally removing your chastity belt.",
    "handing him a pink slip.",
    "slowly backing out of the room.",
    "setting off the pyrotechnics display.",
    "toppling the domino mural of ancient Roman porn.",
    "turning off the secret webcam.",
    "launching yourself down the Slip n' Slide into his penis.",
    "washing off all of the blood.",
    "waiting for the judges' score.",
    "awkwardly rushing back to the computer before another song starts.",
    "sidling over the bed, furitively glancing over at him.",
    "realizing you left the blinds open this whole time.",
    "shooting him with a tshirt cannon filled with condoms.",
    "shouting “TAH DAAAAAAAH!”",
    "finding out he left fifteen minutes ago.",
    "toppling out of his lap trying to unhook from the chair.",
    "presenting him with an itemized bill.",
    "asking him if he'd like fries with that.",
    "playing your buttcheeks like a set of bongos.",
    "turning on your flashing LED bodysuit.",
    "spinning your neck 360 degrees and devouring his soul.",
    "passing out due to the effort.",
    "collapsing into sexy singularity.",
    "ripping off your undewear to reveal a skin colored morphsuit.",
    "bringing out a banjo to really start this hootenanny.",
    "pleading for Jabba the Hutt to release you.",
    "flinging your bra in his face like a rubber band.",
    "triple flipping onto his penis.",
    "picking up your tips from the edge of the stage.",
    "wriggling your eyebrows “Eeeeeh? EEEEEHHH?”",
    "slamming an antique Gibson guitar into the ground.",
    "getting lost in the music, forgetting the point entirely.",
    "showering him in used scratch-off ticket confetti.",
  ]
];
