var dirtyTalkExamples = [
  [
    "Men love dirty talk!",
    "Take <i>in</i> the trash... with dirty talk!",
    "Get vocal in the bedroom!",
    "Start talking dirty!",
    "Even clean girls can talk dirty!",
    "Talk dirty to him!",
  ],
  " ",
  [
    "When he's inside you",
    "Just before he's inside you",
    "After he's had his orgasm",
    "When you're in the car together",
    "When it's time for love",
    "While you're getting your freak on",
    "While thinking of your previous boyfriend"
  ],
  ", ",
  [
    "say",
    "shout",
    "say",
    "try saying",
    "tell him",
    "whisper",
    "scream"
  ],
  " “",
  [
    "Your penis is totally fine, all things considered.",
    "I'm not really sure what the point of all <i>this</i> is!",
    "Great green globs of greasy, grimy, gopher guts / Mutilated monkey meat / Hairy pickled piggy feet / French fried eyeballs floating in some kerosene / and me without a spoon",
    "Okay.",
    "Dirt!",
    "I really love the 2001 David Spade movie ‘Joe Dirt’.",
    "Bawitdaba da bang a dang diggy diggy diggy said the boogy said up jump the boogy",
    "These immigrants are coming over here and taking all of our goddamn jobs!",
    "I consent to everything taking place right now and believe that I will inform you if and when that changes.",
    "Is that a piece of beef jerky?",
    "I didn't think it was possible for sex to jump the shark, and yet <i>here we are</i>.",
    "So do you want go to your mother's tomorrow, or Wednesday?",
    "If you feel anything, it's just the spare key to the house I keep in my uterus.",
    "Pachouli is a perfectly natural smell.",
    "The sins you committed can never be washed away",
    "Out, damned spot! Out, I say!—One, two. What, will these hands ne'er be clean?",
    "Let the bodies hit the floor, let the bodies hit the floor",
    "Double, double, toil and trouble, dick inflamed and jizz cum bubble!",
    "This will burn 600 calories!",
    "My erogenous zones are feeling quite nice now.",
    "Welcome to the danger zone!",
    "For twelve years, you have been asking: Who is John Galt? This is John Galt speaking. I am the man who loves his life. I am the man who does not sacrifice his love...",
    "Crafting mechanics are a waste of gaming resources.",
    "Secret sex moves discovered by local mom - sex coaches hate her!",
    "My vagina is its own country, and you just declared war on my clitoris.",
    "<i>That's</i> not my vagina!",
    "Okay, you're gonna need to turn right at the cervix, then...",
    "And they said replacing my vagina with a cantalope would be a <i>bad</i> thing!",
    "A problem has been detected and Windows has been shut down to prevent damage to your computer.",
    "Oh shit, cramp, CRAMP! CRAMP IN MY FOOT!",
    "The end of the <i>Truman Show</i> was kinda bullshit, if you think about it.",
    "01000110 01101001 01110110 01100101 00100000 01101101 01101001 01101110 01110101 01110100 01100101 01110011 00100000 01110100 01101111 00100000 01110011 01100101 01111000 00100000 01100100 01100101 01110011 01110100 01110010 01110101 01100011 01110100",
    "-.. . .- .-. / . .-.. .. --.. .- --..-- / - .... .. ... / - .-. ..- .-.. -.-- / .. ... / .- / - . .-. .-. .. -... .-.. . / ..-. ..- -.-. -.- / .. .----. -- / .... .- ...- .. -. --.",
    "I just ejected an entire fruit salad from my anus.",
    "Keep checking out my sweet undercarriage while I go vroom vroom into orgasm",
    "Look, I'm not going to lie, my orgasm sounds like the din of a thousand screaming crows.",
    "COME ON AND SLAM, AND WELCOME TO THE JAM.",
    "Shhhh, big boys don't cry.",
    "If you drop below 55 thrusts per minute, I will explode.",
    "Smile! You're on Candid Camera!!",
    "OMG your dick is hilarious! I'm <i>so</i> putting this up on YouTube.",
    "You wouldn't steal a car.",
    "Hey, apropos of nothing, do you feel about the movie <i>Teeth</i>?",
    "Want to try something I saw on Clips for Sale?",
    "My milk shake brings all the boys to the yard / And they're like / It smells like prawns",
    "I'm sorry, the vagina you are trying to reach cannot be located. Please pull out and try again.",
    "Please download Sexr from the Apple store to access this vagina.",
    "Mount my Dew and give me a Code Red in my cherry.",
    "Mama Mia, thatsa spicy meatball!",
    "Millenials are coming to kill you next.",
    "I AM THE ONE WHO CUMS!",
    "Fuck my pussy like it's an offshore tax haven.",
    "If we have a threesome with your doppleganger, is it incest or masturbation?",
    "Baby I hope you're AdBlock because <i>this site</i> is covered in viruses!",
    "And to think, Mother said I'd never amount to ANYTHING! Who's laughing now, Mother!?",
    "I'm the strudel, you're the poppy seed filling.",
    "I understand you've got a family to feed, but I can't offer you a promotion until your metrics improve.",
    "YOU CAN'T PUT YOUR DICK IN HERE! YOU'LL REGRET THIS!",
    "That'll do pig, that'll do.",
    "Dicks are my art, jizz, my medium.",
    "Oh I wonder, wonder, wonder what's in YOUR wonder ball?",
    "Don't you touch that dial, we've got a rockin' cockin' here in my cooch up next.",
    "...did you leave the oven on?",
    "I didn't know pearl necklaces could be so watery.",
    "Workin' in the fuck mine / Goin' down, down, down / Workin' in a fuck mine / Oops, let the dick down",
    "Impale my hot gash with your love stake."
  ],
  "” He's sure to ",
  [
    "put up with it!",
    "blow his top!",
    "notice.",
    "lose his mind!",
    "call the police!",
    "orgasm into outer space!",
    "be confused!",
    "orgasm immediately!",
    "pack up his dick and go home!",
    "come back for more!",
    "have a heart attack!",
    "remember <i>that</i> one.",
    "brag to his friends about you!",
    "return the favor!"
  ]
];
