var dirtyTalkExamples = [
  [
    "Men love dirty talk!",
    "Take IN the trash... with dirty talk!",
    "Get vocal in the bedroom!",
    "Start talking dirty!",
    "Even clean girls can talk dirty!",
    "Talk dirty to him!",
  ],
  " ",
  [
    "When he's inside you",
    "Just before he's inside you",
    "After he's had his orgasm",
    "When you're in the car together",
    "When it's time for love",
    "While you're getting your freak on",
    "While thinking of your previous boyfriend"
  ],
  ", ",
  [
    "say",
    "shout",
    "say",
    "try saying",
    "tell him",
    "whisper",
    "scream"
  ],
  " “",
  [
    "Your penis is totally fine, all things considered.", "I'm not really sure what the point of all <i>this</i> is!",
    "Great green globs of greasy, grimy, gopher guts / Mutilated monkey meat / Hairy pickled piggy feet / French fried eyeballs floating in some kerosene / and me without a spoon",
    "Okay.",
    "Dirt!",
    "I really love the 2001 David Spade movie ‘Joe Dirt’.",
    "Bawitdaba da bang a dang diggy diggy diggy said the boogy said up jump the boogy",
    "These immigrants are coming over here and taking all of our goddamn jobs!",
    "I consent to everything taking place right now and believe that I will inform you if and when that changes.",
    "5/10 effort at <i>best</i>.",
    "...is that a piece of beef jerky?",
    "I didn't think it was possible for sex to jump the shark, and yet <i>here we are</i>.",
    "So do you want go to your mother's tomorrow, or Wednesday?",
    "If you feel anything, it's just the spare key to the house I keep in my uterus.",
    "Pachouli is a perfectly natural smell.",
    "The sins you committed can never be washed away",
    "Out, damned spot! Out, I say!—One, two. What, will these hands ne'er be clean?",
    "Let the bodies hit the floor, let the bodies hit the floor",
    "Double, double, toil and trouble, dick inflamed and jizz cum bubble!",
    "This will burn 600 calories!",
    "My erogenous zones are feeling quite nice now.",
    "Welcome to the danger zone!",
    "For twelve years, you have been asking: Who is John Galt? This is John Galt speaking. I am the man who loves his life. I am the man who does not sacrifice his love...",
    "Crafting mechanics are a waste of gaming resources.",
    "Secret sex moves discovered by local mom - sex coaches hate her!",
    "My vagina is its own country, and you just declared war on my clitoris.",
    "That's not my vagina...",
    "Okay, you're gonna need to turn right at the cervix, then...",
    "And they said replacing my vagina with a cantalope would be a <i>bad</i> thing!",
    "A problem has been detected and Windows has been shut down to prevent damage to your computer. The problem seems to be cause by the following file: vagina.exe",
    "Oh shit, cramp, CRAMP, CRAMP IN MY FOOT.",
    "The end of the <i>Truman Show</i> was kinda bullshit, if you think about it.",
    "SCREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "01000110 01101001 01110110 01100101 00100000 01101101 01101001 01101110 01110101 01110100 01100101 01110011 00100000 01110100 01101111 00100000 01110011 01100101 01111000 00100000 01100100 01100101 01110011 01110100 01110010 01110101 01100011 01110100",
    "-.. . .- .-. / . .-.. .. --.. .- --..-- / - .... .. ... / - .-. ..- .-.. -.-- / .. ... / .- / - . .-. .-. .. -... .-.. . / ..-. ..- -.-. -.- / .. .----. -- / .... .- ...- .. -. --.",
    "I just ejected an entire fruit salad from my anus.",
    "Keep checking out my sweet undercarriage while I go vroom vroom into orgasm",
    "Aww yeah you just bought yourself a one-way ticket to FLAVORTOWN!",
    "Look, I'm not going to lie, my orgasm sounds like the din of a thousand screaming crows."
  ],
  "” He's sure to ",
  [
    "put up with it!", "blow his top!", "notice.", "lose his mind!", "call the police!", "orgasm into outer space!", "Baker Act you!"
  ]
];
