var doThingsToHisGenitals = [
  preambles,
  " ",
  [
    "Punch",
    "Bite",
    "Kick",
    "Poke",
    "Belittle",
    "Humiliate",
    "Spit on",
    "Lick",
    "Have contempt for",
    "Suck",
    "Massage",
    "Hypnotize",
    "Livestream",
    "Skin",
    "Paint",
    "Toast",
    "Roll",
    "Blend",
    "Imagine",
    "Critique",
    "Corkscrew",
    "Experiment with",
    "Mock",
    "Shape",
    "Spin",
    "Tickle",
    "Bounce",
    "Wiggle",
  ],
  " his ",
  maleGenitals,
  " until he ",
  [
    "asks you to stop.",
    "begs you to stop.",
    "wishes you would stop.",
    "summons a genie to get you to stop.",
    "gets bored of it.",
    "calls Amnesty International.",
    "cries.",
    "regrets meeting you.",
    "gets creeped out.",
    "accepts you as his new God.",
    "notices.",
    "wakes up.",
    "finally enjoys it.",
    "bursts into song",
    "calls you <i>Mother</i>.",
    "folds into singularity.",
    "returns to dust.",
    "runs out of quarters.",
    "remembers you exist.",
    "trancends to a new plane.",
    "runs out of the house screaming.",
    "reconsiders a kind and loving god.",
    "has to go on set.",
    "detaches his penis and escapes.",
    "his penis falls off and sprouts two heads in its place.",
    "loans you his Playstation.",
    "admits pineapple is an acceptable pizza topping.",
    "unplugs you from the wall.",
    "sings the entirety of “I Am the Very Model of a Modern Major General”.",
    "buys that mixer you've been asking for.",
    "hands over the microfiche.",
    "remembers your anniversary.",
    "finally reveals the secret Coke recipe.",
    "admits that he faked his Xbox gamer score.",
    "scratch your nipples like a DJ turntable.",
    "starts fingering a jar of silly putty.",
    "gives you the pizza for free.",
    "curls up into a defensive position.",
    "is found Not Guilty by a jury of his peers.",
    "penis ejects a tiny red BANG flag.",
    "quits having sex with his girlfiend.",
    "hears a fanfare play in the background.",
    "gets fed up and does it himself.",
    "ski-bi dibby dib yo da dub dubs into orgasm.",
    "lets you leave the bunker."
  ]
];
