var doThingsToHisGenitals = [
  preambles,
  " ",
  [
    "Punch",
    "Bite",
    "Kick",
    "Poke",
    "Belittle",
    "Humiliate",
    "Spit on",
    "Lick",
    "Have contempt for",
    "Suck",
    "Massage",
    "Hypnotize",
    "Livestream",
    "Skin",
    "Paint",
    "Toast",
    "Roll",
    "Blend",
    "Imagine",
    "Critique",
    "Corkscrew",
    "Experiment with",
    "Align",
    "Mock",
    "Shape",
    "Spin",
    "Tickle"
  ],
  " his ",
  maleGenitals,
  " until he ",
  [
    "asks you to stop.",
    "begs you to stop.",
    "wishes you would stop.",
    "summons a genie to get you to stop.",
    "gets bored of it.",
    "calls Amnesty International.",
    "cries.",
    "regrets meeting you.",
    "gets creeped out.",
    "accepts you as his new God.",
    "notices.",
    "wakes up.",
    "finally enjoys it.",
    "busts into song",
    "calls you <i>Mother</i>.",
    "folds into singularity.",
    "returns to dust.",
    "runs out of quarters.",
    "remembers you exist.",
    "trancends to a new plane.",
    "runs out of the house screaming.",
    "reconsiders a kind and loving god.",
    "has to go on set.",
    "detaches his penis and escapes.",
    "his penis falls off and sprouts two heads in its place.",
    "loans you his Playstation.",
    "admits pineapple is an acceptable pizza topping.",
    "unplugs you from the wall."
  ]
];
