var doThingsToHisGenitals = [
  preambles,
  " ",
  [
    "Punch",
    "Bite",
    "Kick",
    "Poke",
    "Belittle",
    "Humiliate",
    "Spit on",
    "Lick",
    "Have contempt for",
    "Suck",
    "Massage",
    "Hypnotize",
    "Livestream",
    "Skin",
    "Paint",
    "Toast",
    "Roll",
    "Blend",
    "Imagine",
    "Critique",
    "Corkscrew",
    "Experiment with",
    "Align",
    "Mock"
  ],
  " his ",
  maleGenitals,
  " until he ",
  [
    "asks you to stop.",
    "begs you to stop.",
    "wishes you would stop.",
    "summons a genie to get you to stop.",
    "gets bored of it.",
    "calls Amnesty International.",
    "cries.",
    "regrets meeting you.",
    "gets creeped out.",
    "accepts you as his new God.",
    "notices.",
    "wakes up.",
    "finaly enjoys it.",
    "busts into song",
    "calls you Mother",
    "folds into singularity",
    "returns to dust",
    "runs out of quarters.",
    "remembers you exist.",
    "trancends to a new plane.",
    "runs out of the house screaming."
  ]
];