var dressUpAndSay = [
  [
    "Dress up",
    "Greet him at the door dressed",
    "Suprise him by dressing",
    "Throw away the sweatpants and dress"
  ],
  " ",
  [
    "as the thing he fears the most",
    "as his favorite professional golfer",
    "as Robocop",
    "as Scrooge McDuck",
    "in his unwashed socks",
    "like a cross between Prince and his mother",
    "like a mouse",
    "as Soviet Spy Ethel Rosenberg",
    "in your sexiest lingerie",
    "in your birthday suit",
    "as his favorite anime character",
    "as the Cat in the Hat",
    "as a third grade lunchlady",
    "as a caring girlfriend",
    "as a carnival barker",
    "a sentient Bop-It",
    "as the Thing",
    "as a plate of spaghetti",
    "as Sylvia Plath imitating literal jar of bells",
    "as an opera singer",
    "as the personification of dignity",
    "as a giant fish stick",
    "as a large bee",
    "as David Niven era James Bond",
    "Daenerys, Mother of Dragons",
    "as a knock-off Casper",
    "as Darth Vader",
    "as a tin of anchovies",
	"as Rodney Dangerfield in Caddyshack",
	"as Edvard Munch's The Scream",
	"in his mother's clothes",
	"as Margaret Thatcher",
	"in your nicest dirndl",
  "in your sparklewolf fursuit",
  "in a Civil War Era ball gown",
  "in a Garfield costume",
  "as a large jelly roll",
  "as a Silent Hill nurse",
  "as a wendigo",
  "in dazzle camo",
  "as an Easy Bake Oven",
  "as a plate of nachos",
  "as a caricature of yourself"
  ],
  " ",
  [
    "and tell him",
    "and whisper",
    "and scream",
    "and text him",
    "and semaphore him",
    "and sing to him",
    "and mime",
    "and howl",
    "and call out",
    "and screech",
    "and mutter"
  ],
  " ",
  [
    "“You are on trial for the crimes of all humanity. If found guilty, you will be executed.”",
    "“Prepare yourself for disappointment!”",
    "that you want to listen to U2's entire discography before having sex.",
    "“Me Chinese, me play joke. Me put pee-pee in your Coke.”",
    "“Chemtrails are a government conspiracy to ruin sex by giving me nausea.”",
    "“Today I'm going to roleplay as someone cares about you.”",
    "“VACCINES CAUSE AUTISM.”",
    "“Jet fuel can't melt steel beams.”",
    "“So it's $300 for the first two hours, and $100 for each subsequent hour.”",
    "“I think we should see other people”",
    "“Eccelston was the best Doctor.”",
    "“The rhythm method truly is the best way.”",
    "“Dear Leader's turn is next.”",
    "“I like the way you work it”",
    "“If you fuck at 88mph, my vagina catches fire and you'll teleport into the future.”",
    "“My vagina is actually the missing horcrux”",
    "“Is this going to take awhile? I've got a thing...”",
    "“Fuck my pot of gold with your skinny leprechaun”",
    "“You said you were going to dress up as Johnny Depp!”",
    "“Trick or Treat!”",
    "“Chicka Chicka Boom Boom, your dick is in my womb.”",
    "“Fuck, you really <i>are</i> a basic bitch.”",
    "“No, no, the OTHER hole.”",
    "“Sir, this is a McDonalds drive thru.”",
    "“Find a penis, pick it up, and all day you'll have good fuck.”",
	"“There are two doors and two guards, one of them always lies, the other one always tells the truth.”"
    "“Chemicals in the water are turning the frogs gay!”",
    "“I'm a little sexpot short and smug, here is my pussy and here are my jugs”",
    "“I read the WikiHow article on sex and now I'm an expert!”",
    "“Nothing can stop garbage ape.”",
    "“Ramburgler my meat hatch, you daring frycook of industry!”",
    "“Willy wang winkie wanks willingly within warm wombs.”",
    "“DID BECKY EVER DO THIS FOR YOU?!!?”",
    "“Drop the pigs blood, lock the door, and we'll get this <i>Carrie</i> show on the road!”",
    "[Please Insert Joke Here]"
  ]
];
