var handjobs = [
  [
    "Grab his penis and",
    "Take his penis and",
    "Put his penis in your hand and",
    "Reach for his penis and",
    "Ask to see his penis and",
    "When he's not looking, grab his penis and",
    "Contemplate his penis, then",
    "Unsheath his penis, then",
    "Scare his penis from its warren and"
  ],
  " ",
  [
    "stroke it as quickly and forcefully as possible, ignoring any new sounds or smells that occur as a result.",
    "explain why you're disappointed.",
    "list the Kings of England chronologically, excluding the Williams and Henrys.",
    "roll it back and forth between your palms until it is the length and circumference of a No 2 pencil.",
    "immediately let go of it.",
    "strangle it until it goes limp.",
    "measure it, tutting all the while.",
    "give it a hundred thousand tiny papercuts.",
    "name the Martha Stewart swatch its color most resembles.",
    "make a “Chicago Style” Hot Dog with yellow mustard, sport peppers, pickle relish and celery salt.",
    "start a Twitterbot for it.",
    "grab it with your other set of hands now.",
    "rub-a-dub-dub put that dick in a tub.",
    "put some creative arrangements of seasonal flowers around it, adding soft lighting and take a few photos. Remember to only use the Willow filter.",
    "push it back into his body.",
    "twist it into a balloon dog.",
    "throw it on the grill on high for five minutes.",
    "turn it in to the authorities for a sizable reward.",
    "shrug your shoulders, confused at it's bizarre shape.",
    "glue a small toupee on the tip.",
    "loop it around your wrist like a bangle.",
    "insert it into a vending machine.",
    "sing it a lullaby.",
    "feed it a steady diet of castor oil.",
    "pickle it with dill, peppers, and garlic.",
    "present it with an Oscar for Best Supporting Genital",
    "cut his dick into pieces, this is your last resort.",
    "tar and feather it for its heinous crimes.",
    "realize that this dick has been <i>dead for six years</i>.",
    "sharpen it on the strop for a real cutting edge handjob.",
    "clothe it in a tiny dress and take it to prom.",
    "dye it purple and enter it into the county fair as an eggplant.",
    "wiggle it back and forth to the theme of Pink Panther.",
    "shake shake shake, shake shake shake, shake that penis.",
    "give it a failing grade for it's pathetic attempts in PE class.",
    "see if it can tell the difference between Pepsi and Coke.",
    "use it to break into and hotwire a car.",
	"use it as a conductor's wand for the entirety of Disney's Fantasia.",
	"stir your coffee with it.",
	"use it as an obstacle for your hottest fingerboard tricks."
  ]
];
