// jshint -W117
var hideAnItem = [
  preambles,
  " Hide ",
  [
    "an eggplant",
    "a dozen eggs",
    "some hamburger meat",
    "your panties",
    "your underwear",
    "your bra",
    "an (ahem) adult item",
    "a vibrator",
    "a tube of lipstick",
    "loose change",
    "six fluid ounces of massage oil",
    "an empty beer bottle",
    "a Scotch bonnet pepper",
    "baby teeth purchased from the Dark Web",
    "a tampon",
    "Exhibit A",
    "a bowl of clam chowder",
    "the Ark of the Covenant",
    "a large swarm of wasps",
    "Nana's ashes",
    "a <i>Sex for Dummies</i> book",
    "a crisp fiver",
    "your frozen placenta",
    "Gwyneth Paltrow's Goop",
    "your bitcoin wallet code",
    "a series of tasteful used lube bottles",
    "an old cum covered sock",
    "the evidence of your sins",
    "eggs you pickled in your vagina",
    "a vibrator you bought used on eBay",
    "two slices of pepperoni and mushroom pizza",
    "yourself",
    "a box of wiffle condoms",
    "a recently fallen meteorite",
    "the supersoldier serum",
    "the holy materia",
    "a series of nesting matryoshka penis dolls",
    "his internet browsing history",
    "a fleshlight",
    "a xenomorph egg",
    "an old H.R. Giger painting"
  ],
  " in his ",
  [
    "pants pocket",
    "shirt pocket",
    "suit jacket",
    "socks",
    "slippers",
    "nicest dress shoes",
    "dinner",
    "underwear",
    "sex toys chest",
    "throat cavity",
    "escape hatch",
    "briefcase",
    "laptop",
    "workstation",
    "car",
    "truck",
    "onesie",
    "pajamas",
    "banana hammock",
    "thong",
    "hair gel",
    "shaving cream",
    "coat pocket",
    "boss' coat pocket",
    "report for the Big Client on Thursday",
	"xanax jar",
	"gas tank",
	"rice maker",
	"terrarium",
	"Super Nintendo",
	"fireplace",
	"overalls",
	"Lego collection"
  ],
  ". When he ",
  [
    "discovers your treasure",
    "finds it",
    "finds your treat",
    "catches on",
    "figures it out",
	"realizes what you've done",
    "catches you"
  ],
  ", ",
  [
    "say “I've been dead for so long I forget what living feels like.”",
    "shrug your shoulders and sing “That's why they call it the blues”.",
    "give him a seductive wink and an Easter egg dying kit.",
    "punch him in the throat.",
    "yank forcefully on his testicles until he starts crying.",
    "tell him you wanted to give him something to remember you by, as you suspect he has early onset dimensia.",
    "deny EVERYTHING.",
    "call the police.",
    "tell him that he has five minutes to find the antidote.",
    "say “Where we're going, we don't need eyes to see.”",
    "tear out of your fleshly shell and devour him whole",
    "drop him through the trap door into the acid pit below.",
    "introduce him to all of your plushies.",
    "bake a pile of pebbles and swear they are cookies.",
    "pull out the hidden camera and yell “IT'S JUST A PRANK BRO!”",
    "admit that you spent the entire yearly budget on a herd of Chincoteague horses.",
    "try to lure his penis out with yogurt covered raisins.",
    "jump out of the bushes, tackle him, and steal his wallet.",
    "tell him to look into the camera and say “Bang Bros”.",
    "laugh menacingly while hunched over your grand pipe organ.",
    "stand stock still until he forgets you're there",
    "cover yourself in mud and hide in the jungle.",
    "roll out from under the bed, chanting unknowable hymns.",
    "challenge him to an arm westling match to win your estranged son's love.",
    "strip naked on the spot, revealing your many Na'vi tattoos.",
    "jerk him off with a mint condition Power Glove.",
    "wrestle him to the ground and do a victory pose on his unconcious body.",
	"you've won. You now own him.",
	"burst out of a large, hollow cake with dildo sparklers.",
	"dump a Gatorade container of lube on him to congratulate him!",
	"tell him he's passed the test, and can impregnate you on the solar eclipse.",
	"noogie his testicles and call him sport.",
	"lock him out of the house and press your boobs on the glass to mock him.",
	"exit your bedroom covered head to toe in strap-ons.",
	"convince him that this was his idea all along.",
	"accuse him of witchcraft and turn him into the elder council.",
	"sing the Katie Perry's <i>Peacock</i> but get the lyrics wrong.",
    "beatbox <i>Paralyzer</i> while stripping.",
    "shoot him with a dart gun from his deer blind."
  ]
];
