var newSexPositions = [
  [
    "Try out a new position:",
    "Have sex in a new position:",
    "Ditch the missionary!",
    "Forget the kama sutra, try this one:",
    "If you're daring:",
    "If you're up for a challenge:",
    "Get yourself into one of these hardcore positions:"
  ],
  " Put your legs ",
  [
    "over his head",
    "around his butt",
    "on top of his legs",
    "on his knees",
    "over his gun rack",
    "all around his body",
    "aside",
    "out the window",
    "around your neck",
    "on the jungle gym",
    "on the pillow",
    "in the CAT position",
    "on the kitchen table",
    "on the coffee table",
    "on the repilca Great Pyramid of Giza",
    "on the door jamb",
    "on his Dragonlance collection",
	"through the steering wheel",
	"in the stirrups",
	"in the crane position",
  "in the lotus position",
  "in the nearby woodchipper",
  "in a frenzy",
  "over his shoulders"
  ],
  " and your hands ",
  [
    "on his head",
    "gripping his butt cheeks tightly",
    "grabbing his legs",
    "squeezing his knees",
    "resting on his balls",
    "around his aura",
    "on his hip",
    "over his eyes",
    "in his chest cavity",
    "in his mouth",
    "on your phone",
    "in a box of Cheez-Its",
    "on the Bible",
    "against his pubic bone",
    "in a pair of wool mittens",
    "in his buttcrack",
    "around his tulpa",
    "around your breasts",
    "on your trusty six shooter",
	"anywhere warm",
  "on his temples",
  "on his testicles",
  "on his pecs",
  "on his throat"
  ],
  ". ",
  [
    "Now thrust back against him as hard as you can.",
    "Now lay perfectly still until he forgets you're in the room.",
    "Now stare him right in the eyes and dare him to make love to you like that.",
    "Now tell him to orgasm on the count of three.",
    "Now begin a high pitched shriek daring him to knock you unconscious.",
    "Now fire a starter pistol.",
    "Now grind your clitoris into a fine paste.",
    "Now make a bridge with your genitals.",
    "Now don't forget the asshole!",
    "Now neglect to mention your affair.",
    "Now embrace the ~~**~~uNiCoRn oRgAsM~~**~~ within.",
    "Now prepare a fine meal for our guest judges using the mystery ingredient Hot Cheetos.",
    "Now lay back and think of England",
    "Now ask your partner for a spot.",
    "Now execute the legendary quadruple salchow onto the bed.",
	  "Now search for that ring you lost inside him but haven't brought up the courage to say.",
    "Now engulf the both of you in a silk cocoon to complete the metamorphasis.",
    "Now compete in the 17th Annual Company Sack Race.",
    "Now wake up from your nightmare, having remembered nothing but sadness.",
    "Now reconsider all of the life choices you've made up 'til now.",
    "Now fight to the death for the claim to the throne.",
    "Now long for the sweet release of death.",
    "Now get jumpin and bumpin and pumpin and moving all around.",
    "Now ram your genitals together like a game of Hungry Hungry Hippos.",
    "Now realize that you will never be as funny as Lasagna Cat. Ever.",
    "Now slam an entire beer and crush the can on your partner's head.",
    "Now give him the ol' razzle dazzle!",
    "Now create shadow puppets with your genitals.",
    "Now you know your hips don't lie and you're starting to feel it's right."
  ],
  " ",
  [
    "What a workout!",
    "How transcendental!",
    "Soon you'll be another story in Hustler!",
    "Your yoga class will be impressed!",
    "Hotter than hot!!",
    "This makes for an explosive orgasm!",
    "Like a science experiment!",
    "You never knew your body could bend that way!",
    "Sensational sensations!"
  ]
];
