var nonPenisActionsFromMen = [
  fakeNames.first.men,
  " ",
  fakeNames.last,
  " ",
  [
    "says",
    "tells us",
    "confesses",
    "writes"
  ],
  " “",
  [
    "I love it when",
    "It turns me on when",
    "It drives me wild when",
    "I feel like I've died and gone to heaven when"
  ],
  " ",
  [
    "a chick",
    "a woman",
    "a babe",
    "a lady",
    "a girl",
    "my waifu",
    "my bae",
    "a lady"
  ],
  " ",
  [
    "tugs on",
    "slaps",
    "twists",
    "flicks",
    "spits on",
    "lightly touches",
    "silently judges",
    "nibbles on",
    "stares intently at",
    "screams at",
    "cries on",
    "makes a sandwich out of",
    "alternates an ice pack and hot water bottle on",
    "burns",
    "dribbles chocolate sauce on",
    "films",
    "pickles",
    "liveblogs"
  ],
  " my ",
  bodyParts,
  ". It ",
  [
    "drives me crazy every time",
    "absolutely destroys me each time",
    "makes me want to propose marriage",
    "makes me want to do the same thing back to her",
    "makes me rethink all my life choices up til that point",
    "really is something we men sure do like a lot",
    "makes me want to flee the country",
    "makes for a great Reddit post",
    "helps me finish my screenplay",
    "is an amazing revalation",
    "sustains me emotionally",
    "scratches that itch",
    "is really quite inopportune",
    "is a war crime",
    "threatens me emotionally",
    "makes me consider real estate on the moon",
    "fixes my credit score",
    "sends me to Hogwarts",
    "sorts my biscuits",
    "really gives me something to discuss with my therapist this week"
  ],
  [
    "!", "!", "!!!", "."
  ],
  "”"
];