// jshint -W117
var sensualMensTips = [
  " “When I ",
  [
    "lean in to kiss you",
    "take you by the hand",
    "stroke your clit",
    "look into your eyes",
    "touch your chest",
    "finger you",
    "bend you over the bed",
    "load you into the sex swing",
    "mount you from behind",
    "touch you gently",
    "caress your legs",
    "worship your feet",
    "push back your hair",
    "paint your nipples with glittery lipstick",
    "lick your neck",
    "spoon with you in bed",
	"join you in the shower"
  ],
  ", ",
  [
    "spin your head all the way around like you are possessed by the devil",
    "go AWWWWWOOOOOOOO AWWWWOOOOOOOOO AWWWWOOOOOOOOO until you run out of oxygen and pass out",
    "apologize for everything you've ever said to me in the past",
    "pretend that your name is actually my name and refer to me only as ‘Star Commander’",
    "just start going ‘I whip my hair back and forth, I whip my hair back and forth’ and don't stop no matter what",
    "drink to forget",
    "open your mouth to unleash a plague of locusts",
    "turn out the lights and bask in the glow of my bioluminescence",
    "release ink from your pouch and escape from me in the confusion",
    "angle your butt into the air at a perfect 90 degrees",
    "twist your legs into a pretzel",
    "solve the puzzlebox and send us into the hell dimension",
    "create a new World of Warcraft account",
    "protect the payload instead of running off",
    "projectile vomit until blood comes out",
    "stick your hand up my ass and control me like a puppet",
    "create a boondoggle of a park using creatures from the late Jurassic period",
    "offer me up to the elder gods",
    "start singing <i>This Little Piggy</i> and wiggling my toes",
    "hit all of the pressure points and send me into paralysis",
    "crawl out of a TV and curse me with whiskey dick for seven months",
    "snap into my dick like a Slim Jim",
    "use psychometry to find out where my penis has been.",
    "swaddle me in a blanket and rock me to sleep.",
    "blow raspberries on my stomach long past the point of humor into discomfort",
    "pretend my pecs are drums and play the Police's <i>Message in a Bottle</i> with your hands",
    "dive through the plate glass window and run to freedom",
    "place the thrown condom you made in pottery class on my penis",
    "mime whale noises while opening and closing my ass cheeks",
    "shove red jasper up my anus while chanting “We can fuck until the dawn, making love 'til magic's gone”",
    "wear your favorite three penis moon shirt",
    "hide Easter eggs in my anus",
    "create a Kerbal space rocket that resembles my dick",
    "eat cold spaghettios straight from the can",
    "assimilate me into the sexy Borg collective",
    "make cooing noises at my penis",
    "accept that I will <i>never</i> stop wearing diapers",
    "knead my balls into a loaf of rustic bread.",
    "DDoS my favorite porn websites",
    "inspire me to have a greater apprecation for life because <i>you're just so quirky!</i>",
    "turn up the thermostat to 116° and sell me a glass of icewater",
    "estimate how many frozen turkeys could fill the room",
    "order me a model train set through your Amazon Echo",
    "dirty talk in iambic pentameter",
    "focus attention to my vestigial limb(s)",
    "PVR C-SPAN",
    "throw streamers around the room",
    "change my Twitch page settings so people don't join expecting to see a Dota 2 stream",
    "rejuvinate your vagina with alum powder douche",
    "scare the absolute shit out of me to activate the fight or flight response",
    "use Russian Twitter bots to accuse me of having a tiny penis",
    "offer my heart up to Quetzalcoatl",
    "set up a dick jousting duel with my rival, competing for your affection",
    "touches me trantrically instead of sexually",
    "schedules a Google Alert for when we can have sex"
  ],
  ". ",
  [
    "It's tender, yet sexy.",
    "It really shows me your sensual side.",
    "It shows me how much you care.",
    "It demonstrates that you're a classy woman.",
    "Because my previous girlfriend never would."
  ],
  "”",
  "<br />",
  "-",
  fakeNames.first.men,
  ", ",
  [
    24,25,26,27,28,29,30,31,32,33,34,35,36,37
  ]
];
