var suggestionsFromWomen = [
  fakeNames.first.women,
  " ",
  fakeNames.last,
  " ",
  [
    "tells us",
    "writes",
    "wrote in to say",
    "confessed to us",
    "let us know"
  ],
  " “",
  [
    "My husband",
    "My hubby",
    "My boyfriend",
    "My man",
    "My bae",
    "My sweetie",
    "My sister's husband",
    "This guy I know",
    "Chad",
	"My last tinder hookup",
  ],
  " ",
  [
    "loves it when",
    "really likes it when",
    "goes wild when",
    "thinks he's died and gone to heaven when"
  ],
  " ",
  [
    "I give him a long, slow blowjob while struggling to read Simone de Beauvoir's The Second Sex.",
    "we spend an entire evening avoiding eye contact with each other.",
    "I jerk on his dick to the beat of Kid Rock's Early Mornin' Stoned Pimp.",
    "we compare our credit scores from Experian to the ones from Equifax.",
    "we play ‘Sexy Monopoly’, which is like regular Monopoly except it takes longer.",
    "I give him a sexy striptease to the Johnny Cash cover of “Hurt”.",
    "I put googly eyes on his penis and practice ventriloquy.",
    "I show him all my favorite speedruns of games in the Bubsy series.",
    "I describe and rate every hair on his balls.",
    [
      "we record a new episode of our podcast ",
      [
        "“Dick's Nixon”, where I debate his neo-conservative dick on the legacy of Richard Nixon",
        "“Lady And The Dick”, where his dick and I discuss our favorite Disney films.",
        "about our top 100 MMA fights of all time.",
		"“Slamilton”, where we rank each song from Hamilton based on how much it distracts us from having sex.",
        "“The Bone Zone”, where we talk about skeletons we'd like to fuck.",
        "“Half in the Vag”, where we describe in loving detail celebrity vaginas.",
        "“Gotta Go Cum”, where we read our favorite Sonic erotic fan fictions.",
        "“98.6% Intangible”, where we talk about challenge coins for 8 hours.",
        "“Savage Love”, where we list things we love about Fred Savage.",
        "“Welcum to Spermvale”, our serial about an radio announcers sexy adventures in a strange town."
      ]
    ],
    "we watch unboxing videos together.",
    "I strap a large piece of dirty drywall to my face and tell him I'm his glory hole.",
    "I buff his dick to a mirror shine.",
    "I perform my comedy monologue in a Big Bird costume.",
    "I put the lotion on its skin.",
    "I flap my arms and scream like a pterodactyl.",
    "I donate to the FPlus podcast.",
    "we use sexy dice but all the sides are Pomegranate and Dick.",
    "I invest all of our funds in overpriced, over engineered Silicon Valley kitchen appliances.",
    "I use his penis in a tasteful still life.",
    "I jiggle his balls like dice in a cup.",
    "I milk his penis like a cow udder.",
	"I berate him in front of the other girls in the book club.",
	"I let him win a game of Steal the Bacon.",
  "we wrestle in a pool of slimy elbow noodles.",
  "we mosh pit naked in our bedroom.",
  "I go along with his Zeus otherkin story.",
  "I accept that he will never stop wearing diapers.",
  "I wear old-timey prospector wig and pajamas and open the butt flap.",
  "I edit his articles on Wikipedia.",
  "I do a fan dance with handfuls of live snakes.",
  "we try to orgasm before finishing the elevator game."
  ],
  " ",
  [
    "It certainly makes for an interesting evening!",
    "Waiter? Check Please!",
    "We just make sure the door is locked first!",
    "What a rush!",
    "The police know where we live!",
    "Maximum fun!",
    "A sure-fire turn on!",
    "We couldn't keep our hands off each other!",
    "He always asks for more!"
  ],
  "”"
];
